/** Fruit pairs — same image appears twice on the board. */
export const FRUITS = [
  { name: "Apple", emoji: "🍎" },
  { name: "Banana", emoji: "🍌" },
  { name: "Grapes", emoji: "🍇" },
  { name: "Orange", emoji: "🍊" },
  { name: "Strawberry", emoji: "🍓" },
  { name: "Peach", emoji: "🍑" },
  { name: "Cherries", emoji: "🍒" },
  { name: "Kiwi", emoji: "🥝" },
  { name: "Pineapple", emoji: "🍍" },
  { name: "Watermelon", emoji: "🍉" },
  { name: "Mango", emoji: "🥭" },
  { name: "Pear", emoji: "🍐" },
  { name: "Blueberries", emoji: "🫐" },
  { name: "Lemon", emoji: "🍋" },
  { name: "Coconut", emoji: "🥥" },
  { name: "Melon", emoji: "🍈" },
  { name: "Avocado", emoji: "🥑" },
  { name: "Tomato", emoji: "🍅" },
];
